code_commit
sensebox/books-v2 pull request #148
Opened 2020-01-16 10:02 UTC by yhallowiegeht

2020-01-20 08:09 UTC, mariopesch requested changes

2020-01-20 08:09 UTC, mariopesch commented on de/komponenten/sensoren/decibel_meter.md
> +<div class="description">Dieser Sensor misst Geräusche und gibt die Messwerte in Dezibel aus. </div>
misst die Lautstärke

2020-01-20 08:09 UTC, mariopesch commented on de/komponenten/sensoren/decibel_meter.md
> +Im ersten Code-Snippet lesen wir lediglich die Eingangsspannung aus und konvertieren diese in Dezibel um. Der Wert wird auf der Konsole in Arduino angezeigt.
"lesen wir" vermeiden und durch "wird lediglich die Eingangsspannung ausgelesen"

2020-01-20 08:09 UTC, mariopesch commented on de/komponenten/sensoren/decibel_meter.md
> +Hier wollen wir nun die ausgelesenen Werte auf der OseM darstellen. Für eine solche Zeitleiste ist es vorteilhaft z.B. den gemittelten Wert von einer Minute (ggf. 10 Minuten) zu benutzen, da wenn man
Zeitleiste?

2020-03-04 13:15 UTC, yhallowiegeht commented
added into:
- typos&hotfixes_edu
- techbook
close this request now

2020-03-04 13:15 UTC, closed without merging